export const WALLET_CONNECT = "WALLET_CONNECT";
export const WALLET_DISCONNECT = "WALLET_DISCONNECT";
export const WALLET_UPDATE = "WALLET_UPDATE";
export const GET_PROJECT_INFO = "GET_PROJECT_INFO";
export const WALLET_MODAL_SHOW = "WALLET_MODAL_SHOW";
export const WALLET_MODAL_HIDE = "WALLET_MODAL_HIDE";

// UX/UI
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDDEN = "ALERT_HIDDEN";

// TRADE - Project
export const PROJECT_RETIREVEING = "PROJECT_RETIREVEING";
export const PROJECT_UPDATE = "PROJECT_UPDATE";
export const PROJECT_ERROR = "PROJECT_ERROR";

// TRADE - Order
export const MY_ORDER_RETIREVEING = "MY_ORDER_RETIREVEING";
export const MY_ORDER_UPDATE = "MY_ORDER_UPDATE";
export const MY_ORDER_ERROR = "MY_ORDER_ERROR";
