export const WALLET_CONNECT = "WALLET_CONNECT";
export const WALLET_DISCONNECT = "WALLET_DISCONNECT";
export const GET_PROJECT_INFO = "GET_PROJECT_INFO";

// UX/UI
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDDEN = "ALERT_HIDDEN";