export const WALLET_CONNECT = "WALLET_CONNECT";
export const WALLET_DISCONNECT = "WALLET_DISCONNECT";
export const WALLET_UPDATE = "WALLET_UPDATE";
export const WALLET_MODAL_SHOW = "WALLET_MODAL_SHOW";
export const WALLET_MODAL_HIDE = "WALLET_MODAL_HIDE";

export const GET_PROJECT_INFO = "GET_PROJECT_INFO";

// FUND
export const PROJECT_INFO_RETIREVEING = "PROJECT_INFO_RETIREVEING";
export const PROJECT_INFO_UPDATE = "PROJECT_INFO_UPDATE";
export const PROJECT_INFO_UPDATE_BY_PROJECT_ADDRESS = "PROJECT_INFO_UPDATE_BY_PROJECT_ADDRESS";
export const PROJECT_INFO_ERROR = "PROJECT_INFO_ERROR";


// UX/UI
export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";
export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDDEN = "ALERT_HIDDEN";

// TRADE - Project
export const PROJECT_RETIREVEING = "PROJECT_RETIREVEING";
export const PROJECT_UPDATE = "PROJECT_UPDATE";
export const PROJECT_ERROR = "PROJECT_ERROR";

// TRADE - Order
export const MY_ORDER_RETIREVEING = "MY_ORDER_RETIREVEING";
export const MY_ORDER_UPDATE = "MY_ORDER_UPDATE";
export const MY_ORDER_ERROR = "MY_ORDER_ERROR";


// Currency
export const CURRENCY_RETIREVEING = "CURRENCY_RETIREVEING";
export const CURRENCY_UPDATE = "CURRENCY_UPDATE";
export const CURRENCY_ERROR = "CURRENCY_ERROR";